{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fastapi-demo.fullname" . }}-secret
  namespace: {{ include "fastapi-demo.namespace" . }}
  labels:
    {{- include "fastapi-demo.labels" . | nindent 4 }}
type: Opaque
data:
{{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}
