{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: {{ include "fastapi-demo.fullname" . }}-servicemonitor
  labels:
    app: {{ include "fastapi-demo.name" . }}

spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fastapi-demo.name" . }}

  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}