apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: fastapi-demo
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Pjain047/fastapi-demo-gitops
    targetRevision: main

    path: helm/fastapi-demo

  destination:
    server: https://kubernetes.default.svc
    namespace: fastapi-demo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true